extends:
  - "spectral:oas"
  - "@stoplight/spectral-owasp-ruleset"

rules:
  # --- Structural Quality ---
  operation-operationId: error
  operation-operationId-unique: error
  operation-description: warn
  operation-tags: warn
  path-params: error
  no-eval-in-markdown: error
  no-script-tags-in-markdown: error
  typed-enum: warn
  oas3-valid-media-example: warn
  oas3-valid-schema-example: warn

  # --- Security ---
  # No auth is required for this API, so operation-security checks are disabled.
  oas3-operation-security-defined: off

  # --- Naming Conventions (customize to your style) ---
  # Uncomment and adjust as needed:
  # path-casing:
  #   severity: error
  #   given: "$.paths"
  #   then:
  #     function: pattern
  #     functionOptions:
  #       match: "^\/[a-z][a-z0-9-\/{}]*$"

  # --- Response Quality ---
  operation-success-response: error

  # --- Description Quality ---
  info-description: warn
  info-contact: warn
  info-license: off

  # --- Server Configuration ---
  oas3-api-servers: warn
  oas3-server-trailing-slash: error

  # --- OWASP API Security Top 10 (2023) ---
  # All OWASP rules set to error severity.
  # Rules already at error by default are listed for explicitness.

  # API1:2023 - Broken Object Level Authorization
  owasp:api1:2023-no-numeric-ids: error

  # API2:2023 - Broken Authentication
  # Rules that prevent insecure auth patterns are kept in case auth is added later.
  # Rules that require auth to be present are disabled to simplify agent implementation challenges.
  owasp:api2:2023-no-http-basic: error
  owasp:api2:2023-no-api-keys-in-url: error
  owasp:api2:2023-no-credentials-in-url: error
  owasp:api2:2023-auth-insecure-schemes: error
  owasp:api2:2023-jwt-best-practices: off
  owasp:api2:2023-short-lived-access-tokens: off
  owasp:api2:2023-write-restricted: off
  owasp:api2:2023-read-restricted: off

  # API3:2023 - Broken Object Property Level Authorization
  owasp:api3:2023-no-additionalProperties: error
  owasp:api3:2023-constrained-additionalProperties: error
  owasp:api3:2023-no-unevaluatedProperties: error
  owasp:api3:2023-constrained-unevaluatedProperties: error

  # API4:2023 - Unrestricted Resource Consumption
  owasp:api4:2023-rate-limit: error
  owasp:api4:2023-rate-limit-retry-after: error
  owasp:api4:2023-rate-limit-responses-429: error
  owasp:api4:2023-array-limit: error
  owasp:api4:2023-string-limit: error
  owasp:api4:2023-string-restricted: error
  owasp:api4:2023-integer-limit: error
  owasp:api4:2023-integer-limit-legacy: error
  owasp:api4:2023-integer-format: error

  # API5:2023 - Broken Function Level Authorization
  owasp:api5:2023-admin-security-unique: error

  # API7:2023 - Server Side Request Forgery
  owasp:api7:2023-concerning-url-parameter: error

  # API8:2023 - Security Misconfiguration
  owasp:api8:2023-define-cors-origin: error
  owasp:api8:2023-no-scheme-http: error
  owasp:api8:2023-no-server-http: error
  owasp:api8:2023-define-error-validation: error
  owasp:api8:2023-define-error-responses-401: off
  owasp:api8:2023-define-error-responses-500: error

  # API9:2023 - Improper Inventory Management
  owasp:api9:2023-inventory-access: error
  owasp:api9:2023-inventory-environment: error
